server:
  port: 9988
management:
  health:
    #    defaults:
    elasticsearch:
      enabled: false
spring:
  application:
    name: yzp-business
  #    # 配置 DataSource Driver
  #    datasource:
  #     driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  #    # 指定 YAML 配置文件
  #     url: jdbc:shardingsphere:classpath:bootstrap.yml

  #  profiles:
  #    active: dev
  config:
    import:
      - nacos:yzp-business.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec
