spring:
  application:
    name: yangzp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yzp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convert_to_null&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  redis:
    database: 6
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30000ms
        min-idle: 1
    #password:
    port: 6379
    timeout: 6000ms
server:
  port: 9988
