server:
  port: 9989
spring:
  application:
    name: yzp-business-two
  config:
    import:
      - nacos:yzp-business-two.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec
