server:
  port: 9981
spring:
  application:
    name: yzp-gateway
#  main:
#    web-application-type: reactive
  #  profiles:
#    active: dev
  config:
    import:
      - nacos:yzp-gateway.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec