server:
  port: 9982
spring:
  application:
    name: yzp-auth
#  profiles:
#    active: dev
  config:
    import:
      - nacos:yzp-auth.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: ab14df3f-840a-46e6-a3d4-a0ae080a53ec